<a href="https://colab.research.google.com/github/mirzarenardi01/Basic-Phyton-Programming-for-Data-Science/blob/main/Tugas_Matriks_Pada_Python_Numpy_Mirza_(1800015063).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np

# 1. Membuat Numpy Array

In [113]:
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])
print(array1)
print(array1.shape) # ukuran array
print(array1.dtype) # tipe data elemen array
print(array1.ndim)
print(array1.size) # jumlah elemen
print(array1.itemsize)

[1 3 5 7 2 4 6 8]
(8,)
int64
1
8
8


In [111]:
array2 = np.array([9, 11, 13, 15, 10, 12, 14, 16])
print(array2)
print(array1[array2 < 15])

[ 9 11 13 15 10 12 14 16]
[1 3 5 2 4 6]


# 2. Vektor dengan Numpy Array

In [25]:
a = np.array([3,1,3,2,3,3,3,4])
b = np.array([5, 4, 7, 8, 3, 9, 2, 1])
c = np.arange(1,11,2)
print(a)
print(b)
print(c)

[3 1 3 2 3 3 3 4]
[5 4 7 8 3 9 2 1]
[1 3 5 7 9]


# 3. Operasi Vektor

a. Penjumlahan

In [28]:
hasil = a + b
print(hasil)

[ 8  5 10 10  6 12  5  5]


b. Pengurangan

In [27]:
hasil = a - b
print(hasil)

[-2 -3 -4 -6  0 -6  1  3]


c. Perkalian dengan scalar

In [30]:
hasil = 3*c
print(hasil)

[ 3  9 15 21 27]


# 4. Matriks dengan Numpy Array

In [40]:
data1 = np.array([[1, 2], [3, 4], [5, 6]])
data1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
data2 = 2*data1
data2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [41]:
data1[0, 1]

2

In [42]:
data1[1:4]

array([[3, 4],
       [5, 6]])

In [43]:
data1[0:3, 1]

array([2, 4, 6])

# 5. Operasi Matriks

a. Penjumlahan

In [47]:
hasil = data1 + data2
print(np.transpose(hasil))

[[ 3  9 15]
 [ 6 12 18]]


b. Pengurangan

In [48]:
hasil = data2 - data1
print(hasil)

[[1 2]
 [3 4]
 [5 6]]


c. Perkalian dengan scalar

In [50]:
4*data1

array([[ 4,  8],
       [12, 16],
       [20, 24]])

d. Perkalian matriks

In [56]:
hasil = data1 * data2
print(hasil)

[[ 2  8]
 [18 32]
 [50 72]]


# 6. Dot Product dan Cross Product

In [123]:
data1 = np.array([[1, 2], [3, 4], [5, 6]])
data2 = data1.T
# perkalian dot
c1 = np.dot(data1, data2)
print(c1)

[[ 5 11 17]
 [11 25 39]
 [17 39 61]]


In [109]:
data1 = np.array([[1, 2], [3, 4], [5, 6]])
data2 = np.array([[2, 4], [0, 8], [3, 9]])
# perkalian cross
c2 = np.cross(data1,data2)
print(c2)

[ 0 24 27]


# 7. Aljabar Linear dengan Numpy

a. Inverse Matriks

In [83]:
data1 = np.array([[3, 4], [5, 6]])
# inverse
c = np.linalg.inv(data1)
print(c)


[[-3.   2. ]
 [ 2.5 -1.5]]


b. Determinan

In [84]:
data1 = np.array([[3, 4], [5, 6]])
# determinant
c = np.linalg.det(data1)
print(c)


-1.9999999999999971


c. Mengambil Elemen Diagonal

In [89]:
data1 = np.array([[3, 4], [5, 6]])
# diag
c = np.diag(data1)
print(c)

# diag on a vector returns diagonal matrix (overloaded function)
c = np.diag([2,3])
print(c)

[3 6]
[[2 0]
 [0 3]]


d. Solve Persamaan Linear

In [93]:
data1 = np.array([[3, 4], [5, 6]])
data3 = np.array([6,18])
print(data1)
print(data3)

data1_inv = np.linalg.inv(data1)

# menyelesaikan persamaan linear
X1 = np.dot(data1_inv,data3)
print(X1)

# cara lain
X2 = np.linalg.solve(data1,data3)
print(X2)
# menyelesaikan persamaan linear
X1 = np.dot(data1_inv,data3)
print(X1)

# cara lain
X2 = np.linalg.solve(data1,data3)
print(X2)

[[3 4]
 [5 6]]
[ 6 18]
[ 18. -12.]
[ 18. -12.]
[ 18. -12.]
[ 18. -12.]


# 8. Principal Component Analysis (PCA) dengan Numpy

In [95]:
import numpy as np
import pandas as pd
from numpy.linalg import eig
X =np.array([[60, 11, 100],[72, 12, 125], [84, 11, 150], [96, 12, 200]])
print(X)
mean_X = np.mean(X.T, axis=1, dtype=np.int)
print(mean_X)

[[ 60  11 100]
 [ 72  12 125]
 [ 84  11 150]
 [ 96  12 200]]
[ 78  11 143]


In [96]:
center_X= (X - mean_X)
print(center_X)

[[-18   0 -43]
 [ -6   1 -18]
 [  6   0   7]
 [ 18   1  57]]


In [97]:
covariance = np.cov(center_X.T)

In [98]:
value, vector = eig(covariance)
print(value.astype(int))

[2055    7    0]


In [99]:
vector_with_highest_eigenvalue= vector[:,[0,1]]
PCA_calc = vector_with_highest_eigenvalue.T.dot(center_X.T)
print(PCA_calc.T)

[[-46.54989389  -2.46724497]
 [-18.96229166   0.34651824]
 [  8.61254741   3.28644517]
 [ 59.73679925  -2.29989451]]


Menggunakan sklearn

In [100]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
pca= PCA(n_components=2)
pca.fit(X)
PCA_value= pca.transform(X)
print(PCA_value)

[[-47.25918417  -2.18370096]
 [-19.67158194   0.63006226]
 [  7.90325713   3.56998919]
 [ 59.02750897  -2.01635049]]
